angular.module('angularPromises',['ngRoute','promiseModule'])
.config(function($routeProvider){
  $routeProvider.when("/",{
      templateUrl:"promises/promise.html",
      controller:"promiseCtrl",
  });
  $routeProvider.otherwise({
      redirectTo:"/"
  });
});